### PR TITLE
Update ubi.ini

### PR DESCRIPTION
**Pull request by WestZekro**

### CODE REVIEW

**Comment by SuiMachine** [comment]
Language should be set by installer itself after installing using ini properties (e.g. https://github.com/SuiMachine/Hype-The-Time-Quest-Installer/blob/master/Hype-Alternate-Installer.iss#L148)

**Comment by WestZekro** [comment]
Hi thx for your reply but when i start the installer it says there is no
strings.eng but on my disk is a string.ger

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am So., 1. Sept. 2019 um 11:30 Uhr schrieb SuiMachine <
notifications@github.com>:

**Comment by SuiMachine** [comment]
https://github.com/SuiMachine/Hype-The-Time-Quest-Installer/commit/5aaaa7a93c2d8f69597a309cbe5df84e9e6166c5

This should hopefully fix it. Although it's been a while since I used Inno setup script.
Exe download: https://github.com/SuiMachine/Hype-The-Time-Quest-Installer/blob/master/bin/Hype%20-%20The%20Time%20Quest%20Alternate%20Installer%201.0.0.exe

**Comment by WestZekro** [comment]
Thank you very much, now it works ^^ 

Gesendet von Mail für Windows 10

Von: SuiMachine
Gesendet: Dienstag, 3. September 2019 20:45
An: SuiMachine/Hype-The-Time-Quest-Installer
Cc: WestZekro; State change
Betreff: Re: [SuiMachine/Hype-The-Time-Quest-Installer] Update ubi.ini (#1)

5aaaa7a
This should hopefully fix it. Although it's been a while since I used Inno setup script.

**Pull request closed without merging**
